version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://thepeoplepitch:${DB_PASSWORD}@db:5432/thepeoplepitch
      - SECRET_KEY=${SECRET_KEY}
      - CRON_API_KEY=${CRON_API_KEY}
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=thepeoplepitch
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=thepeoplepitch
    restart: always

  updater:
    build:
      context: .
      dockerfile: Dockerfile.updater
    environment:
      - APP_URL=http://app:5000
      - CRON_API_KEY=${CRON_API_KEY}
    depends_on:
      - app
    restart: always

volumes:
  postgres_data:
