# For Railway deployment - defines the startup command
[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app_production:app"
healthcheckPath = "/health"
restartPolicyType = "on_failure"
